baseurl = "https://wamisnet.github.io"
languageCode = "ja-jp"
title = "わみめも"
theme = "hugo-future-imperfect-slim"
preserveTaxonomyNames = true
paginate = 10.0
disqusShortname = "wamisnet"
googleAnalytics = "UA-62256925-7"
pluralizeListTitles = false
enableRobotsTXT = true
canonifyURLs = true
DefaultContentLanguage  = "ja"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [
  "html",
  "json"
]

[params]
description = "私が作ったコードやハードウエアのはなし"
images = ["/img/main/wami.jpg"]
navbarTitle = "わみめも"
viewMorePostLink = "/blog/"
enableCDN = false
cssFiles = ["default"]
jsFiles = ["default"]
highlightjs = true
highlightjsTheme = "github"
highlightjsLang = [
  "html",
  "css",
  "js",
  "c",
  "c++"
]
viewMorePostsLink = "/blog/"
readingTime = false
socialShare = [
  "twitter",
  "facebook",
  "email"
]

  [params.meta]
  description = "NefryやSofmoといった開発者向けボードを作ったり、AndroidやFlutterアプリ作ったり、Webで遊んでみたり、手当たり次第になんでもやっちゃう人のサイト"
  author = "wami"
  favicon = false
  svg = true
  faviconVersion = "1"
  msColor = "#ffffff"
  iOSColor = "#ffffff"

  [params.header]
  navbarTitle = "わみめも"
  dynamicTitles = false
  searchMenu = false
  shareMenu = false
  languageMenu = false

  [params.intro]
  header = "わみめも"
  paragraph = "NefryやSofmoといった開発者向けボードを作ったり、AndroidやFlutterアプリ作ったり、Webで遊んでみたり、手当たり次第になんでもやっちゃう人のサイト"
  rssIntro = true
  socialIntro = true
  hideWhenSingleColumn = false
  alwaysOnHomepage = false

    [params.intro.pic]
    src = "/img/main/wami.jpg"
    shape = "circle"
    width = "100"
    alt = "wami"

  [params.sidebar]
  about = "NefryやSofmoといった開発者向けボードを作ったり、AndroidやFlutterアプリ作ったり、Webで遊んでみたり、手当たり次第になんでもやっちゃう人<br>やってること<br>・ IoTデバイスNefryシリーズの開発、販売<br>・ 基板やファームを含むハードウエアやWeb、Androidアプリの受託開発<br>・ 専門学校やハンズオンなどの講師<br>・「同人ハードウェアmeetup」 #dhwmu や名古屋版IoTLTなどイベントの主催"
  postAmount = 8.0
  categories = true
  categoriesByCount = true

  [params.footer]
  rssFooter = true
  socialFooter = true

  [params.staticman]
  enabled = false
  api = ""
  gitProvider = ""
  username = ""
  repo = ""
  branch = ""

    [params.staticman.recaptcha]
    siteKey = ""
    encryptedKey = ""

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  pre = "<i class='fa fa-home'></i>"
  weight = 1.0

  [[menu.main]]
  name = "About"
  url = "/about/"
  pre = "<i class='fa fa-id-card'></i>"
  weight = 2.0

  [[menu.main]]
  name = "Blog"
  url = "/blog/"
  pre = "<i class='far fa-newspaper'></i>"
  weight = 3.0

  [[menu.main]]
  name = "Product"
  url = "/itemized/"
  pre = "<i class='fa fa-list'></i>"
  weight = 4.0

  [[menu.main]]
  name = "Contact"
  url = "/contact/"
  pre = "<i class='far fa-envelope'></i>"
  weight = 5.0

  [[menu.main]]
  name = "Small Business"
  url = "/business/"
  pre = "<i class='fa fa-id-card'></i>"
  weight = 6.0

[social]
github = "wamisnet"
twitter = "wamisnet"
email = "wamiwami@live.jp"
