
version: 2
jobs:
  build:
    docker:
      - image: klakegg/hugo:0.73.0-ext-ubuntu-onbuild
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./Deploy.sh
      - run:
          name: Upload to Deploy
          command: ./Deploy.sh
