
version: 2
jobs:
  build:
    branches:
      only:
        - write
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./Deploy.sh
      - run:
          name: Upload to Deploy
          command: ./Deploy.sh
