
version: 2
jobs:
  build:
    docker:
      - image: klakegg/hugo:latest
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./Deploy.sh
      - run:
          name: Upload to Deploy
          command: ./Deploy.sh
