backend:
  name: github
  repo: wamisnet/wamisnet.github.io
  base_url: https://us-central1-wamihomepage.cloudfunctions.net
  auth_endpoint: /oauth/auth
  branch: write # Branch to update (optional; defaults to master)
locale: 'ja'
media_folder: static/img/blog
public_folder: /img/blog
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'タイトル', name: 'title', widget: 'string' }
      - { label: '公開日時', name: 'date', widget: 'datetime' }
      - { label: '説明文', name: 'description', widget: 'string' }
      - { label: '本文', name: 'body', widget: 'markdown' }
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        required: false
      - label: "categories"
        name: "Categories"
        widget: "list"
        allow_add: true
        required: false
      - { label: "ファイル名【初回のみ】", name: "slug", widget: "string",required: false}
      - { label: "アイキャッチ画像", name: "featured", widget: "image",required: false}
      - { label: "アイキャッチ画像説明文", name: "featuredalt", widget: "string",required: false}
  - name: 'product'
    label: 'Product'
    folder: 'content/itemized'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'business'
    label: 'Business'
    folder: 'content/business'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
